# Generated by Django 5.1.2 on 2025-05-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentapilog',
            name='link_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentapilog',
            name='action',
            field=models.CharField(choices=[('INITIATE', 'Initiate Payment'), ('FETCH_SESSION', 'Fetch Session'), ('GET_ORDER', 'Get Existing Order'), ('CREATE_LINK', 'Create Payment Link'), ('ERROR', 'Error')], max_length=50),
        ),
    ]
