# Generated by Django 5.1.2 on 2025-06-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentapilog_link_id_alter_paymentapilog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentapilog',
            name='action',
            field=models.CharField(choices=[('INITIATE', 'Initiate Payment'), ('FETCH_SESSION', 'Fetch Session'), ('GET_ORDER', 'Get Existing Order'), ('CREATE_LINK', 'Create Payment Link'), ('WEBHOOK', 'Webhook'), ('ERROR', 'Error')], max_length=50),
        ),
    ]
