# Generated by Django 5.1.2 on 2025-07-19 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0011_remove_payment_order_remove_transaction_payment_and_more'),
        ('payments', '0003_alter_paymentapilog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentapilog',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='The type of the logged object (Order or SubscriptionOrder).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='paymentapilog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='The ID of the logged object.', null=True),
        ),
        migrations.AlterField(
            model_name='paymentapilog',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Legacy foreign key to Order (do not use for new logs).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
