# Generated by Django 5.1.2 on 2025-07-28 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_customuser_gym'),
        ('payments', '0006_payment_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='accounts.gym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentapilog',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paymentapolog', to='accounts.gym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='accounts.gym'),
            preserve_default=False,
        ),
    ]
