version: '3.9'

services:
  web:
    build: .
    container_name: iron_board_web
    entrypoint: [ "./entrypoint.sh" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: iron_board_db
    environment:
      POSTGRES_DB: iron_board_db
      POSTGRES_USER: iron_board_admin
      POSTGRES_PASSWORD: xPL7y6qe1gLHAg2B9SWvW06vXSC8lxSe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: iron_board_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
