# Generated by Django 5.1.6 on 2025-04-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_tagline', models.CharField(blank=True, max_length=255)),
                ('company_logo', models.ImageField(upload_to='company/')),
                ('company_favicon', models.ImageField(upload_to='company/')),
                ('company_logo_svg', models.FileField(upload_to='company/')),
                ('offline_address', models.TextField()),
                ('map_location', models.URLField(help_text='Google Maps embed URL')),
                ('info_mobile', models.CharField(max_length=20)),
                ('info_email', models.EmailField(max_length=254)),
                ('complaint_mobile', models.CharField(max_length=20)),
                ('complaint_email', models.EmailField(max_length=254)),
                ('sales_mobile', models.CharField(max_length=20)),
                ('sales_email', models.EmailField(max_length=254)),
                ('company_instagram', models.URLField(blank=True)),
                ('company_facebook', models.URLField(blank=True)),
                ('company_email_ceo', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Business Detail',
                'verbose_name_plural': 'Business Details',
            },
        ),
        migrations.DeleteModel(
            name='Config',
        ),
    ]
