# Generated by Django 5.1.6 on 2025-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessdetails_delete_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='closed_days',
            field=models.CharField(blank=True, help_text='Comma-separated days (e.g. Sun,Mon)', max_length=20),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='closing_time',
            field=models.TimeField(default='02:30:45.123456'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='opening_time',
            field=models.TimeField(default='02:30:45.123456'),
            preserve_default=False,
        ),
    ]
