# Generated by Django 5.1.6 on 2025-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businessdetails_closed_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdetails',
            name='closing_time',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AlterField(
            model_name='businessdetails',
            name='opening_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
