# Generated by Django 5.1.6 on 2025-04-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_businessdetails_closing_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.CharField(max_length=255, unique=True, verbose_name='Configuration Key')),
                ('value', models.CharField(max_length=255, verbose_name='Configuration Value')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'ordering': ['config'],
            },
        ),
    ]
