# Generated by Django 5.1.2 on 2025-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='gstn',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
