# Generated by Django 5.1.2 on 2025-04-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_businessdetails_gstn'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='breadcrumb_image',
            field=models.FileField(default=1, upload_to='company/'),
            preserve_default=False,
        ),
    ]
