# Generated by Django 5.1.2 on 2025-04-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_businessdetails_breadcrumb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetails',
            name='about_page_image',
            field=models.FileField(default=1, upload_to='company/'),
            preserve_default=False,
        ),
    ]
