# Generated by Django 5.1.6 on 2025-03-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_socialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='platform',
            field=models.CharField(choices=[('GMAIL', 'Gmail'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('LINKEDIN', 'LinkedIn'), ('PHONE', 'Phone'), ('TWITTER', 'Twitter'), ('YOUTUBE', 'YouTube'), ('WHATSAPP', 'WhatsApp'), ('HOME_PAGE_WHATSAPP', 'Home Page WhatsApp'), ('HOME_PAGE_PHONE', 'Home Page Phone'), ('HOME_PAGE_INSTAGRAM', 'Home Page Instagram'), ('HOME_PAGE_GMAIL', 'Home Page Gmail')], max_length=20, verbose_name='Social Media Platform'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Link or Phone Number'),
        ),
    ]
