# Generated by Django 5.1.2 on 2025-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customer_country_customer_customer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Customer', 'Customer')], max_length=100),
        ),
    ]
