# Generated by Django 5.1.2 on 2025-06-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_staff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, default='Get Info', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(default=1, help_text='E.g. TRAINING HARD', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='tagline',
            field=models.CharField(blank=True, help_text='E.g. SHAPE YOUR BODY', max_length=255),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_highlight',
            field=models.CharField(default=1, help_text='E.g. STRONG', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='title_main',
            field=models.CharField(default=1, help_text='E.g. BE', max_length=255),
            preserve_default=False,
        ),
    ]
