# Generated by Django 5.1.2 on 2025-07-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_banner_button_text_banner_subtitle_banner_tagline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'Manager'), ('Employee', 'Employee'), ('Customer', 'Customer'), ('Member', 'Member'), ('Trainer', 'Trainer')], max_length=100),
        ),
    ]
