# Generated by Django 5.1.2 on 2025-07-15 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_customuser_staff_role'),
        ('products', '0009_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.package'),
        ),
    ]
