# Generated by Django 5.1.2 on 2025-07-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customuser_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='on_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
