# Generated by Django 5.1.2 on 2025-07-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_on_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='employee_id',
            new_name='member_id',
        ),
    ]
