# Generated by Django 5.1.2 on 2025-07-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_employee_id_customuser_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='package_expiry_date',
            field=models.DateField(null=True),
        ),
    ]
