# Generated by Django 5.1.2 on 2025-08-02 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_monthlymembershiptrend'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlymembershiptrend',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlymembershiptrend',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membership_trends', to='accounts.gym'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='monthlymembershiptrend',
            unique_together={('gym', 'year', 'month')},
        ),
    ]
