# Generated by Django 5.1.2 on 2025-08-02 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_monthlymembershiptrend_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='admin',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_administered', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
