# Generated by Django 5.1.2 on 2025-09-11 11:18

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_gym_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country_code',
            field=django_countries.fields.CountryField(blank=True, help_text='Country dialing code', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
