# Generated by Django 5.1.2 on 2025-09-11 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_customuser_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.gym'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gyms_administered', to=settings.AUTH_USER_MODEL),
        ),
    ]
