# Generated by Django 5.1.2 on 2025-08-13 19:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_gym_admin'),
        ('health', '0002_workouttemplate_memberworkoutassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('week_of_year', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('week_index_since_join', models.PositiveIntegerField(db_index=True, editable=False)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(400)])),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('bmi', models.DecimalField(decimal_places=1, editable=False, max_digits=4, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)])),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='accounts.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['gym', 'user', 'date'], name='health_body_gym_id_67e199_idx'), models.Index(fields=['gym', 'user', 'year', 'week_of_year'], name='health_body_gym_id_c3ef33_idx'), models.Index(fields=['gym', 'user', 'week_index_since_join'], name='health_body_gym_id_52854a_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
