# Generated by Django 5.1.6 on 2025-04-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_temporder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporder',
            name='unique_id',
        ),
    ]
