# Generated by Django 5.1.6 on 2025-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_sku',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
