# Generated by Django 5.1.6 on 2025-04-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporder',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
