# Generated by Django 5.1.2 on 2025-07-19 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_temporder_processed'),
        ('products', '0009_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('payment_gateway', models.CharField(default='cashfree', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('auto_renew', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_orders', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='products.package')),
            ],
        ),
    ]
