# Generated by Django 5.1.2 on 2025-07-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_payment_order_remove_transaction_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GooglePayCredentials',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='content_type',
        ),
    ]
