# Generated by Django 5.1.2 on 2025-07-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_delete_googlepaycredentials_and_more'),
        ('subscriptions', '0002_alter_subscription_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
