# Generated by Django 5.1.2 on 2025-07-28 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_customuser_gym'),
        ('orders', '0013_delete_payment_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='accounts.gym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='accounts.gym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.gym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='accounts.gym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_orders', to='accounts.gym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporder',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temp_orders', to='accounts.gym'),
            preserve_default=False,
        ),
    ]
