# Generated by Django 5.1.2 on 2025-09-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_cart_gym_cartitem_gym_order_gym_orderitem_gym_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionorder',
            name='order_number',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
