# Generated by Django 5.1.2 on 2025-07-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_schedule_weekday_alter_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='weekday',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
