# Generated by Django 5.1.2 on 2025-07-12 08:42

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_schedule_end_time_alter_schedule_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrtoken',
            name='expires_at',
            field=models.DateTimeField(default=attendance.models.default_expiry),
        ),
    ]
