# Generated by Django 5.1.2 on 2025-07-26 08:06

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_qrtoken_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
