# Generated by Django 5.1.2 on 2025-07-28 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_customuser_gym'),
        ('attendance', '0006_schedule_schedule_date_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.gym'),
            preserve_default=False,
        ),
    ]
