# Generated by Django 5.1.2 on 2025-07-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_customuser_gym'),
        ('attendance', '0007_schedule_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrtoken',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='accounts.gym'),
            preserve_default=False,
        ),
    ]
