# Generated by Django 5.1.2 on 2025-07-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_customuser_gym'),
        ('attendance', '0008_qrtoken_gym'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.gym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkinlog',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkin_logs', to='accounts.gym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classenrollment',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='accounts.gym'),
            preserve_default=False,
        ),
    ]
