# Generated by Django 5.1.2 on 2025-04-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_options_product_country_of_origin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
