# Generated by Django 5.1.2 on 2025-07-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('duration_days', models.PositiveIntegerField(help_text='Total duration of the package in days')),
                ('price', models.DecimalField(decimal_places=2, help_text='Original price of the package', max_digits=10)),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('flat', 'Flat Amount'), ('percent', 'Percentage')], default='none', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Value of the discount (flat or %)', max_digits=8)),
                ('features', models.JSONField(blank=True, default=dict, help_text="A dictionary of custom features like { 'personal_trainer': true, 'diet_plan': false }")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
