# Generated by Django 5.1.2 on 2025-07-28 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_customuser_gym'),
        ('products', '0009_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='gym',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='accounts.gym'),
            preserve_default=False,
        ),
    ]
